/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package project_euler

import ch.qos.logback.classic.LoggerContext
import ch.qos.logback.core.util.StatusPrinter
import javafx.application.Application
import javafx.fxml.FXMLLoader
import javafx.stage.Stage
import org.slf4j.LoggerFactory
import project_euler.controllers.BaseController.Companion.createAndAttachController
import project_euler.controllers.MainController

fun main(args: Array<String>) {
  StatusPrinter.print(LoggerFactory.getILoggerFactory() as LoggerContext)
  Application.launch(MainApplication::class.java, *args)
}

class MainApplication : Application() {
  override fun start(primaryStage: Stage?) {
    try {
      val fxmlLoader = FXMLLoader().also {
        it.location = ClassLoader.getSystemResource("views/main.fxml")
      }
      primaryStage?.createAndAttachController(MainController.Factory(), fxmlLoader)
      primaryStage?.show()
    } catch (e: Exception) {
      println(e)
    }
  }
}
